FROM mcr.microsoft.com/devcontainers/go:1-1.21-bullseye

# [Optional] Uncomment this section to install additional OS packages.
# RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb && dpkg -i mysql-apt-config_0.8.29-1_all.deb
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends mysql-server

# [Optional] Uncomment the next lines to use go get to install anything else you need
# USER vscode
# RUN go get -x github.com/go-sql-driver/mysql
# USER root

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
